// ============================================================
// DBL Games — game catalog
// Sources (all free-to-embed):
//  1. OnlineGames.io publisher feed:
//     https://www.onlinegames.io/media/plugins/genGames/embed.json
//  2. GameMonetize feed:
//     https://rss.gamemonetize.com/rssfeed.php?format=json&category=All&company=All&amount=30&page=1
//  3. TurboWarp Scratch embeds: https://turbowarp.org/{id}/embed
// Add more games by copying an entry and pasting new values.
// cat options: driving, shooting, arcade, sports, puzzle,
//              clicker, minecraft, 2player, sim, horror
// ============================================================

const GAMES = [
  // ---- Featured (big tiles) ----
  { title: "Highway Traffic", cat: "driving", featured: true,
    embed: "https://www.onlinegames.io/games/2022/unity/highway-traffic/index.html",
    img: "https://www.onlinegames.io/media/posts/32/responsive/Highway-Traffic-2-xs.jpg" },
  { title: "GTA Simulator", cat: "driving", featured: true,
    embed: "https://www.onlinegames.io/games/2023/unity2/gta-simulator/index.html",
    img: "https://www.onlinegames.io/media/posts/416/responsive/GTA-Simulator-xs.jpg" },
  { title: "Steal Brainrot Heist", cat: "arcade", featured: true,
    embed: "https://cloud.onlinegames.io/games/2026/unity/steal-brainrot-heist/game.html",
    img: "https://www.onlinegames.io/media/posts/1180/responsive/steal-brainrot-heist-2-xs.webp" },
  { title: "Dublix", cat: "sim", featured: true,
    embed: "https://cloud.onlinegames.io/games/2025/unity4/dublix/game-og.html",
    img: "https://www.onlinegames.io/media/posts/1126/responsive/dublix-xs.webp" },

  // ---- Driving ----
  { title: "Drift King", cat: "driving",
    embed: "https://www.onlinegames.io/games/2024/unity/drift-king/index.html",
    img: "https://www.onlinegames.io/media/posts/729/responsive/Drift-King-xs.jpg" },
  { title: "Drift Hunters Pro", cat: "driving",
    embed: "https://www.onlinegames.io/games/2023/unity/drift-hunters-pro/index.html",
    img: "https://www.onlinegames.io/media/posts/397/responsive/Drift-Hunters-Pro-xs.jpg" },
  { title: "Madalin Stunt Cars Pro", cat: "driving",
    embed: "https://www.onlinegames.io/games/2023/unity/madalin-stunt-cars-pro/index.html",
    img: "https://www.onlinegames.io/media/posts/401/responsive/Madalin-Stunt-Cars-Pro-Game-xs.jpg" },
  { title: "Escape Car", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2025/unity2/escape-car/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1000/responsive/Escape-Car-xs.jpg" },
  { title: "Burnout City", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2024/unity/burnout-city/index-og.html",
    img: "https://www.onlinegames.io/media/posts/861/responsive/burnoutcity-xs.jpg" },
  { title: "Stickman GTA City", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2024/unity3/stickman-gta-city/index-og.html",
    img: "https://www.onlinegames.io/media/posts/900/responsive/stickman-gta-city-free-xs.jpg" },
  { title: "Highway Racer Pro", cat: "driving",
    embed: "https://www.onlinegames.io/games/2024/unity/highway-racer-pro/index.html",
    img: "https://www.onlinegames.io/media/posts/822/responsive/Highway-Racer-Pro-xs.jpg" },
  { title: "Police Chase Drifter", cat: "driving",
    embed: "https://www.onlinegames.io/games/2021/3/police-chase-drifter/index.html",
    img: "https://www.onlinegames.io/media/posts/155/responsive/Police-Chase-Drifter-Online-xs.jpg" },
  { title: "Police Traffic", cat: "driving",
    embed: "https://www.onlinegames.io/games/2021/unity/police-traffic/index.html",
    img: "https://www.onlinegames.io/media/posts/187/responsive/Pollice-Traffic-xs.jpg" },
  { title: "Super Car Driving", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2024/unity2/super-car-driving/index-og.html",
    img: "https://www.onlinegames.io/media/posts/854/responsive/supercardriving-2-xs.jpg" },
  { title: "Edys Car Simulator", cat: "driving",
    embed: "https://www.onlinegames.io/games/2022/unity/edys-car-simulator/index.html",
    img: "https://www.onlinegames.io/media/posts/238/responsive/Edys-Car-Simulator-Online-xs.jpg" },
  { title: "City Stunts", cat: "driving",
    embed: "https://www.onlinegames.io/games/2023/unity3/city-stunts/index.html",
    img: "https://www.onlinegames.io/media/posts/629/responsive/City-Stunts-Game-xs.jpg" },
  { title: "Real Flight Simulator", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2023/unity2/real-flight-simulator/index.html",
    img: "https://www.onlinegames.io/media/posts/342/responsive/Real-Flight-Simulator-2-xs.jpg" },
  { title: "Bus Subway Runner", cat: "driving",
    embed: "https://www.onlinegames.io/games/2022/unity/bus-subway-runner/index.html",
    img: "https://www.onlinegames.io/media/posts/235/responsive/Bus-Subway-Runner-Game-xs.jpg" },
  { title: "Moto Trials", cat: "driving",
    embed: "https://www.onlinegames.io/games/2021/unity/moto-trials/index.html",
    img: "https://www.onlinegames.io/media/posts/523/responsive/Moto-Trials-xs.jpg" },
  { title: "Monster Truck Mountain Climb", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2021/2/monster-truck-mountain-climb/index-og.html",
    img: "https://www.onlinegames.io/media/posts/924/responsive/monster-truck-mountain-climb-xs.jpg" },
  { title: "Pixel Driver", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2021/unity3/pixel-driver/index-og.html",
    img: "https://www.onlinegames.io/media/posts/990/responsive/Pixel-Driver-xs.jpg" },
  { title: "Offroad Rally", cat: "driving",
    embed: "https://www.onlinegames.io/games/2023/unity2/offroad-rally/index.html",
    img: "https://www.onlinegames.io/media/posts/461/responsive/Offroad-Rally-xs.jpg" },

  // ---- Shooting ----
  { title: "CS Online", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2023/unity2/cs-online/index.html",
    img: "https://www.onlinegames.io/media/posts/434/responsive/CS-Online-xs.jpg" },
  { title: "Masked Special Forces", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2022/unity2/masked-special-forces/index.html",
    img: "https://www.onlinegames.io/media/posts/310/responsive/Masked-Special-Forces-FPS-xs.jpg" },
  { title: "FPS Strike", cat: "shooting",
    embed: "https://cloud.onlinegames.io/games/2024/unity2/fps-strike/index-og.html",
    img: "https://www.onlinegames.io/media/posts/902/responsive/fps-strike-online-xs.jpg" },
  { title: "ArmedForces.io", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2021/unity3/armedforces-io/index.html",
    img: "https://www.onlinegames.io/media/posts/234/responsive/Armed-Forces-io-xs.jpg" },
  { title: "WarStrike", cat: "shooting",
    embed: "https://cloud.onlinegames.io/games/2024/unity3/warstrike/index-og.html",
    img: "https://www.onlinegames.io/media/posts/870/responsive/WarStrike-Online-xs.jpg" },
  { title: "Guerrillas io", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2023/unity2/guerrillas-io/index.html",
    img: "https://www.onlinegames.io/media/posts/423/responsive/Guerillas-io-xs.jpg" },
  { title: "Urban Sniper", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2022/unity2/urban-sniper/index.html",
    img: "https://www.onlinegames.io/media/posts/322/responsive/Urban-Sniper-Game-xs.jpg" },
  { title: "Legendary Sniper", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2021/unity3/legendary-sniper/index.html",
    img: "https://www.onlinegames.io/media/posts/596/responsive/Legendary-Sniper-xs.jpg" },
  { title: "Zombie War Defense", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2022/unity/zombie-war-defense/index.html",
    img: "https://www.onlinegames.io/media/posts/466/responsive/Zombie-War-Defense-Game-xs.jpg" },
  { title: "Mob City", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2021/unity3/mob-city/index.html",
    img: "https://www.onlinegames.io/media/posts/418/responsive/Mob-City-xs.jpg" },

  // ---- Arcade ----
  { title: "Geometry Dash FreezeNova", cat: "arcade",
    embed: "https://www.onlinegames.io/games/2023/q2/geometry-dash-freezenova/index.html",
    img: "https://www.onlinegames.io/media/posts/510/responsive/Geometry-Dash-FreezeNova-xs.jpg" },
  { title: "Crazy Cattle 3D", cat: "arcade",
    embed: "https://cloud.onlinegames.io/games/2025/unity3/crazy-cattle-3d/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1004/responsive/Crazy-Cattle-3D-xs.jpg" },
  { title: "Fall Brainrots", cat: "arcade",
    embed: "https://cloud.onlinegames.io/games/2026/unity/fall-brainrots/game.html",
    img: "https://www.onlinegames.io/media/posts/1194/responsive/fall-brainrots-xs.webp" },
  { title: "Stack Fire Ball", cat: "arcade",
    embed: "https://www.onlinegames.io/games/2021/unity/stack-fire-ball/index.html",
    img: "https://www.onlinegames.io/media/posts/184/responsive/Stack-Fire-Ball-Game-xs.jpg" },
  { title: "Stickman Destruction", cat: "arcade",
    embed: "https://www.onlinegames.io/games/2021/unity3/stickman-destruction/index.html",
    img: "https://www.onlinegames.io/media/posts/233/responsive/Stickman-Destruction-xs.jpg" },
  { title: "Geometry Vector", cat: "arcade",
    embed: "https://cloud.onlinegames.io/games/2026/construct/329/geometry-vector/game.html",
    img: "https://www.onlinegames.io/media/posts/1246/responsive/geometry-vector-xs.webp" },
  { title: "Snaker io", cat: "arcade",
    embed: "https://cloud.onlinegames.io/games/2026/more/snaker-io/game.html",
    img: "https://www.onlinegames.io/media/posts/1261/responsive/snaker-io-xs.webp" },
  { title: "Troll Level", cat: "arcade",
    embed: "https://cloud.onlinegames.io/games/2024/unity2/troll-level/index-og.html",
    img: "https://www.onlinegames.io/media/posts/857/responsive/troll-level-online-xs.jpg" },
  { title: "FNF Funk 3D", cat: "arcade",
    embed: "https://www.onlinegames.io/games/2022/unity/fnf-funk-3d/index.html",
    img: "https://www.onlinegames.io/media/posts/613/responsive/FNF-Funk-3D-xs.jpg" },
  { title: "Backflip Challenge", cat: "arcade",
    embed: "https://cloud.onlinegames.io/games/2026/unity/backflip-challenge/game.html",
    img: "https://www.onlinegames.io/media/posts/1203/responsive/backflip-challenge-xs.webp" },
  { title: "Kick the Alien", cat: "arcade",
    embed: "https://cloud.onlinegames.io/games/2021/4/kick-the-alien/index-og.html",
    img: "https://www.onlinegames.io/media/posts/997/responsive/Kick-the-Alien-xs.jpg" },

  // ---- Sports ----
  { title: "Basket Hoop", cat: "sports",
    embed: "https://cloud.onlinegames.io/games/2024/construct/311/basket-hoop/index-og.html",
    img: "https://www.onlinegames.io/media/posts/843/responsive/Basket-Hoop-xs.jpg" },
  { title: "Basketball io", cat: "sports",
    embed: "https://www.onlinegames.io/games/2022/unity3/basketball-io/index.html",
    img: "https://www.onlinegames.io/media/posts/302/responsive/Basketball-io-2-xs.jpg" },
  { title: "Basketball Slam Dunk", cat: "sports",
    embed: "https://www.onlinegames.io/games/2021/unity2/basketball-slam-dunk/index.html",
    img: "https://www.onlinegames.io/media/posts/200/responsive/Basketball-Slam-Dunk-xs.jpg" },
  { title: "Head Soccer 2022", cat: "sports",
    embed: "https://www.onlinegames.io/games/2023/construct/280/head-soccer-2022/index.html",
    img: "https://www.onlinegames.io/media/posts/624/responsive/Head-Soccer-2022-xs.jpg" },
  { title: "Football King", cat: "sports",
    embed: "https://www.onlinegames.io/games/2024/construct/226/football-king/index.html",
    img: "https://www.onlinegames.io/media/posts/739/responsive/Football-King-xs.jpg" },
  { title: "Car Football", cat: "sports",
    embed: "https://www.onlinegames.io/games/2023/construct/198/car-football/index.html",
    img: "https://www.onlinegames.io/media/posts/405/responsive/Car-Football-xs.jpg" },
  { title: "Golf Bit", cat: "sports",
    embed: "https://cloud.onlinegames.io/games/2026/construct/328/golf-bit/game.html",
    img: "https://www.onlinegames.io/media/posts/1289/responsive/golf-bit-xs.webp" },

  // ---- Puzzle ----
  { title: "Block Blast", cat: "puzzle",
    embed: "https://cloud.onlinegames.io/games/2024/unity3/block-blast/index-og.html",
    img: "https://www.onlinegames.io/media/posts/876/responsive/block-blast-xs.jpg" },
  { title: "Chess FreezeNova", cat: "puzzle",
    embed: "https://cloud.onlinegames.io/games/2025/unity3/chess/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1116/responsive/chess-freezenova-xs.webp" },
  { title: "Tile Match", cat: "puzzle",
    embed: "https://cloud.onlinegames.io/games/2025/unity/tile-match/index-og.html",
    img: "https://www.onlinegames.io/media/posts/939/responsive/tile-match-xs.jpg" },
  { title: "Mahjong", cat: "puzzle",
    embed: "https://cloud.onlinegames.io/games/2025/unity/mahjong/index-og.html",
    img: "https://www.onlinegames.io/media/posts/966/responsive/Mahjong-xs.jpg" },
  { title: "Solitaire", cat: "puzzle",
    embed: "https://cloud.onlinegames.io/games/2025/html/solitaire/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1007/responsive/solitaire-xs.jpg" },
  { title: "Nuts and Bolts Puzzle", cat: "puzzle",
    embed: "https://cloud.onlinegames.io/games/2025/unity/nuts-and-bolts-puzzle/index-og.html",
    img: "https://www.onlinegames.io/media/posts/965/responsive/nuts-and-bolts-puzzle-xs.jpg" },
  { title: "Fire and Water", cat: "puzzle",
    embed: "https://www.onlinegames.io/games/2023/construct/179/fire-and-water/index.html",
    img: "https://www.onlinegames.io/media/posts/469/responsive/Fire-and-Water-xs.jpg" },
  { title: "Find It", cat: "puzzle",
    embed: "https://cloud.onlinegames.io/games/2025/unity/find-it/index-og.html",
    img: "https://www.onlinegames.io/media/posts/940/responsive/Find-It-xs.jpg" },

  // ---- Clicker / Idle ----
  { title: "Cookie Clicker Pro", cat: "clicker",
    embed: "https://cloud.onlinegames.io/games/2025/unity/cookie-clicker-pro/index-og.html",
    img: "https://www.onlinegames.io/media/posts/971/responsive/Cookie-Clicker-Pro-Game-xs.jpg" },
  { title: "Capybara Clicker Pro", cat: "clicker",
    embed: "https://www.onlinegames.io/games/2023/q2/capybara-clicker-pro/index.html",
    img: "https://www.onlinegames.io/media/posts/554/responsive/Capybara-Clicker-Pro-xs.jpg" },
  { title: "Poop Clicker", cat: "clicker",
    embed: "https://www.onlinegames.io/games/2024/construct/292/poop-clicker/index.html",
    img: "https://www.onlinegames.io/media/posts/742/responsive/Poop-Clicker-xs.jpg" },
  { title: "Idle Dev Startup", cat: "clicker",
    embed: "https://www.onlinegames.io/games/2023/unity3/idle-dev-startup/index.html",
    img: "https://www.onlinegames.io/media/posts/566/responsive/Idle-Dev-Startup-Game-xs.jpg" },
  { title: "Nova Craft", cat: "clicker",
    embed: "https://cloud.onlinegames.io/games/2024/more2/nova-craft/index.html",
    img: "https://www.onlinegames.io/media/posts/841/responsive/Nova-Craft-xs.jpg" },

  // ---- Minecraft ----
  { title: "Cube Worlds", cat: "minecraft",
    embed: "https://cloud.onlinegames.io/games/2025/html/cube-worlds/index-og.html",
    img: "https://www.onlinegames.io/media/posts/986/responsive/Cube-Worlds-xs.jpg" },
  { title: "CubeCraft Survival", cat: "minecraft",
    embed: "https://cloud.onlinegames.io/games/2025/unity4/cubecraft-survival/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1113/responsive/cubecraft-survival-xs.webp" },
  { title: "Voxel World", cat: "minecraft",
    embed: "https://cloud.onlinegames.io/games/2025/unity/voxel-world/index-og.html",
    img: "https://www.onlinegames.io/media/posts/937/responsive/voxel-world-xs.jpg" },
  { title: "Survival Craft", cat: "minecraft",
    embed: "https://www.onlinegames.io/games/2022/unity/survival-craft/index.html",
    img: "https://www.onlinegames.io/media/posts/593/responsive/Survival-Craft-Game-xs.jpg" },
  { title: "Survival Island", cat: "minecraft",
    embed: "https://cloud.onlinegames.io/games/2024/unity2/survival-island/index-og.html",
    img: "https://www.onlinegames.io/media/posts/970/responsive/Survival-Island-xs.jpg" },
  { title: "99 Nights in the Forest", cat: "minecraft",
    embed: "https://cloud.onlinegames.io/games/2026/unity/99-nights-in-the-forest-survival/game.html",
    img: "https://www.onlinegames.io/media/posts/1190/responsive/99-nights-in-the-forest-xs.webp" },
  { title: "Pixelmon Town", cat: "minecraft",
    embed: "https://cloud.onlinegames.io/games/2025/html/pixelmon-town/game.html",
    img: "https://www.onlinegames.io/media/posts/1214/responsive/pixelmon-town-xs.webp" },
  { title: "Blocky Parkour Ninja", cat: "minecraft",
    embed: "https://www.onlinegames.io/games/2022/construct/156/blocky-parkour-ninja/index.html",
    img: "https://www.onlinegames.io/media/posts/440/responsive/Blocky-Parkour-Ninja-xs.jpg" },

  // ---- 2 Player ----
  { title: "Get On Top", cat: "2player",
    embed: "https://www.onlinegames.io/games/2024/code/6/get-on-top/index.html",
    img: "https://www.onlinegames.io/media/posts/697/responsive/Get-on-Top-xs.jpg" },
  { title: "Drunken Duel", cat: "2player",
    embed: "https://www.onlinegames.io/games/2024/code/2/drunken-duel/index.html",
    img: "https://www.onlinegames.io/media/posts/698/responsive/Drunken-Duel-xs.jpg" },
  { title: "Rooftop Duel", cat: "2player",
    embed: "https://cloud.onlinegames.io/games/2025/construct/213/rooftop-duel/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1002/responsive/Rooftop-Duel-Online-xs.jpg" },
  { title: "Tank Arena", cat: "2player",
    embed: "https://cloud.onlinegames.io/games/2025/construct/293/tank-arena/index-og.html",
    img: "https://www.onlinegames.io/media/posts/956/responsive/Tank-Arena-Online-xs.jpg" },
  { title: "2 Player Crazy Racer", cat: "2player",
    embed: "https://www.onlinegames.io/games/2022/unity3/2-player-crazy-racer/index.html",
    img: "https://www.onlinegames.io/media/posts/617/responsive/2-Player-Crazy-Racer-xs.jpg" },
  { title: "Super Mini Racing", cat: "2player",
    embed: "https://www.onlinegames.io/games/2022/unity4/super-mini-racing/index.html",
    img: "https://www.onlinegames.io/media/posts/819/responsive/Super-Mini-Racing-xs.jpg" },
  { title: "Skibidi Toilet io", cat: "2player",
    embed: "https://www.onlinegames.io/games/2023/construct/242/skibidi-toilet-io/index.html",
    img: "https://www.onlinegames.io/media/posts/540/responsive/Skibidi-Toilet-xs.jpg" },

  // ---- Simulator / Tycoon ----
  { title: "Fast Food Manager", cat: "sim",
    embed: "https://cloud.onlinegames.io/games/2025/unity4/fast-food-manager/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1114/responsive/fast-food-manager-xs.webp" },
  { title: "Fast Food Rush", cat: "sim",
    embed: "https://cloud.onlinegames.io/games/2025/unity/fast-food-rush/index-og.html",
    img: "https://www.onlinegames.io/media/posts/979/responsive/fast-food-rush-xs.jpg" },
  { title: "Checkout Frenzy", cat: "sim",
    embed: "https://cloud.onlinegames.io/games/2025/unity/checkout-frenzy/index-og.html",
    img: "https://www.onlinegames.io/media/posts/974/responsive/checkout-frenzy-cashier-game-xs.jpg" },
  { title: "Farming Island", cat: "sim",
    embed: "https://cloud.onlinegames.io/games/2025/unity/farming-island/index-og.html",
    img: "https://www.onlinegames.io/media/posts/988/responsive/farming-island-xs.jpg" },
  { title: "Jungle Mart", cat: "sim",
    embed: "https://cloud.onlinegames.io/games/2026/construct/339/jungle-mart/game.html",
    img: "https://www.onlinegames.io/media/posts/1247/responsive/jungle-mart-xs.webp" },
  { title: "War Simulator", cat: "sim",
    embed: "https://www.onlinegames.io/games/2021/unity2/war-simulator/index.html",
    img: "https://www.onlinegames.io/media/posts/821/responsive/War-Simulator-xs.jpg" },
  { title: "Rome Simulator", cat: "sim",
    embed: "https://www.onlinegames.io/games/2021/unity/rome-simulator/index.html",
    img: "https://www.onlinegames.io/media/posts/634/responsive/Rome-Simulator-2-xs.jpg" },
  { title: "Taxi Simulator", cat: "sim",
    embed: "https://www.onlinegames.io/games/2022/unity/taxi-simulator/index.html",
    img: "https://www.onlinegames.io/media/posts/465/responsive/Taxi-Simulator-xs.jpg" },

  // ---- Horror ----
  { title: "Five Nights at Poppy", cat: "horror",
    embed: "https://cloud.onlinegames.io/games/2025/unity2/five-nights-at-poppy/index-og.html",
    img: "https://www.onlinegames.io/media/posts/992/responsive/Five-Nights-at-Poppy-xs.jpg" },
  { title: "Masked Forces Zombie Survival", cat: "horror",
    embed: "https://www.onlinegames.io/games/2021/unity3/masked-forces-zombie-survival/index.html",
    img: "https://www.onlinegames.io/media/posts/225/responsive/Masked-Forces-Zombie-Survival-Online-xs.jpg" },

  // ---- More driving ----
  { title: "Drift Rider", cat: "driving",
    embed: "https://www.onlinegames.io/games/2023/unity3/drift-rider/index.html",
    img: "https://www.onlinegames.io/media/posts/553/responsive/Drift-Rider-xs.jpg" },
  { title: "Drift Fury", cat: "driving",
    embed: "https://www.onlinegames.io/games/2023/unity/drift-fury/index.html",
    img: "https://www.onlinegames.io/media/posts/650/responsive/Drift-Fury-xs.jpg" },
  { title: "Highway Racer 2", cat: "driving",
    embed: "https://www.onlinegames.io/games/2022/unity2/highway-racer-2/index.html",
    img: "https://www.onlinegames.io/media/posts/323/responsive/Highway-Racer-2-xs.jpg" },
  { title: "F1 Drift Racer", cat: "driving",
    embed: "https://www.onlinegames.io/games/2022/construct/134/f1-drift-racer/index.html",
    img: "https://www.onlinegames.io/media/posts/504/responsive/F1-Drift-Racer-xs.jpg" },
  { title: "Crazy Parking Fury", cat: "driving",
    embed: "https://www.onlinegames.io/games/2022/unity3/crazy-parking-fury/index.html",
    img: "https://www.onlinegames.io/media/posts/643/responsive/Crazy-Parking-Fury-xs.jpg" },
  { title: "Stunt Rider", cat: "driving",
    embed: "https://www.onlinegames.io/games/2024/unity/stunt-rider/index.html",
    img: "https://www.onlinegames.io/media/posts/674/responsive/Stunt-Rider-Online-xs.jpg" },
  { title: "Motorbike Traffic", cat: "driving",
    embed: "https://www.onlinegames.io/games/2021/unity/motorbike-traffic/index.html",
    img: "https://www.onlinegames.io/media/posts/419/responsive/Motorbike-Traffic-Game-xs.jpg" },
  { title: "Motorbike Stunt Simulator", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2021/unity/motorbike-stunt-simulator/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1045/responsive/motorbike_stunt_simulator_game-2-xs.webp" },
  { title: "Limousine Simulator", cat: "driving",
    embed: "https://www.onlinegames.io/games/2021/4/limousine-simulator/index.html",
    img: "https://www.onlinegames.io/media/posts/701/responsive/Limousine-Simulator-xs.jpg" },
  { title: "ATV Highway Traffic", cat: "driving",
    embed: "https://www.onlinegames.io/games/2021/unity/atv-highway-traffic/index.html",
    img: "https://www.onlinegames.io/media/posts/668/responsive/ATV-Highway-Traffic-xs.jpg" },
  { title: "Neon Racer", cat: "driving",
    embed: "https://www.onlinegames.io/games/2021/4/neon-racer/index.html",
    img: "https://www.onlinegames.io/media/posts/173/responsive/Neon-Racer-2-xs.jpg" },
  { title: "Futuristic Racer", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2021/2/futuristic-racer/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1051/responsive/futuristic_racer_game-xs.webp" },
  { title: "Egg Car Racing", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2024/construct/289/egg-car-racing/index-og.html",
    img: "https://www.onlinegames.io/media/posts/910/responsive/egg-car-racing-xs.jpg" },
  { title: "Train Racing", cat: "driving",
    embed: "https://www.onlinegames.io/games/2022/construct/120/train-racing/index.html",
    img: "https://www.onlinegames.io/media/posts/445/responsive/Train-Racing-Game-xs.jpg" },
  { title: "Poly Racing Cars", cat: "driving",
    embed: "https://cloud.onlinegames.io/games/2022/unity3/poly-racing-cars/index-og.html",
    img: "https://www.onlinegames.io/media/posts/835/responsive/Poly-racing-cars-image-xs.jpg" },
  { title: "Airplane Racer", cat: "driving",
    embed: "https://www.onlinegames.io/games/2022/unity/airplane-racer/index.html",
    img: "https://www.onlinegames.io/media/posts/268/responsive/Airplane-Racer-xs.jpg" },
  { title: "Crazy Car Arena", cat: "driving",
    embed: "https://www.onlinegames.io/games/2022/unity3/crazy-car-arena/index.html",
    img: "https://www.onlinegames.io/media/posts/317/responsive/Crazy-Car-Arena-Game-xs.jpg" },
  { title: "Army Driver", cat: "driving",
    embed: "https://www.onlinegames.io/games/2022/construct/63/army-driver/index.html",
    img: "https://www.onlinegames.io/media/posts/424/responsive/Army-Driver-xs.jpg" },
  { title: "Monster Truck City Parking", cat: "driving",
    embed: "https://www.onlinegames.io/games/2021/unity/monster-truck-city-parking/index.html",
    img: "https://www.onlinegames.io/media/posts/582/responsive/Monster-Truck-City-Parking-xs.jpg" },

  // ---- More shooting ----
  { title: "Wasteland Shooters", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2021/unity2/wasteland-shooters/index.html",
    img: "https://www.onlinegames.io/media/posts/218/responsive/Wasteland-Shooters-xs.jpg" },
  { title: "Crazy Strike Force", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2023/unity/crazy-strike-force/index.html",
    img: "https://www.onlinegames.io/media/posts/366/responsive/Crazy-Strike-Force-xs.jpg" },
  { title: "Army Combat", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2021/unity/army-combat/index.html",
    img: "https://www.onlinegames.io/media/posts/664/responsive/Army-Combat-xs.jpg" },
  { title: "Deer Hunter", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2021/1/deer-hunter/index.html",
    img: "https://www.onlinegames.io/media/posts/591/responsive/Deer-Hunter-xs.jpg" },
  { title: "Sniper Elite", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2021/1/sniper-elite/index.html",
    img: "https://www.onlinegames.io/media/posts/127/responsive/Sniper-Elite-Online-xs.jpg" },
  { title: "Secret Sniper Agent", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2022/construct/129/secret-sniper-agent/index.html",
    img: "https://www.onlinegames.io/media/posts/753/responsive/Secret-Sniper-Agent-xs.jpg" },
  { title: "Galactic Sniper", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2021/2/galactic-sniper/index.html",
    img: "https://www.onlinegames.io/media/posts/719/responsive/Galactic-Sniper-xs.jpg" },
  { title: "Alien Sky Invasion", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2021/unity3/alien-sky-invasion/index.html",
    img: "https://www.onlinegames.io/media/posts/594/responsive/Alien-Sky-Invasion-xs.jpg" },
  { title: "Battle Royale Simulator", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2022/unity3/battle-royale-simulator/index.html",
    img: "https://www.onlinegames.io/media/posts/633/responsive/Battle-Royale-Simulator-xs.jpg" },
  { title: "Mech Shooter", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2022/unity/mech-shooter/index.html",
    img: "https://www.onlinegames.io/media/posts/649/responsive/Mech-Shooter-xs.jpg" },
  { title: "CobraZ.io Classic", cat: "shooting",
    embed: "https://www.onlinegames.io/games/2022/unity/cobraz-io-classic/index.html",
    img: "https://www.onlinegames.io/media/posts/546/responsive/Cobraz.io-Classic-xs.jpg" },

  // ---- More arcade ----
  { title: "Drako IO", cat: "arcade",
    embed: "https://cloud.onlinegames.io/games/2022/unity/drako-io/game.html",
    img: "https://www.onlinegames.io/media/posts/1304/responsive/drako-io-xs.webp" },
  { title: "Crazy Stickman Physics", cat: "arcade",
    embed: "https://www.onlinegames.io/games/2023/construct/185/crazy-stickman-physics/index.html",
    img: "https://www.onlinegames.io/media/posts/715/responsive/Crazy-Stickman-Physics-xs.jpg" },
  { title: "Snake", cat: "arcade",
    embed: "https://cloud.onlinegames.io/games/2024/phaser/snake/index-og.html",
    img: "https://www.onlinegames.io/media/posts/919/responsive/snake-xs.jpg" },
  { title: "Archer Hero", cat: "arcade",
    embed: "https://www.onlinegames.io/games/2023/unity/archer-hero/index.html",
    img: "https://www.onlinegames.io/media/posts/364/responsive/Archer-Hero-Online-xs.jpg" },
  { title: "Dark Ninja Hanjo", cat: "arcade",
    embed: "https://www.onlinegames.io/games/2023/unity/dark-ninja-hanjo/index.html",
    img: "https://www.onlinegames.io/media/posts/451/responsive/Dark-Ninja-Hanjo-xs.jpg" },

  // ---- More puzzle ----
  { title: "Four Colors", cat: "puzzle",
    embed: "https://www.onlinegames.io/games/2023/code/four-colors/index.html",
    img: "https://www.onlinegames.io/media/posts/535/responsive/Four-Colors-xs.jpg" },
  { title: "Solitaire Adventure", cat: "puzzle",
    embed: "https://www.onlinegames.io/games/2022/unity4/solitaire-adventure/index.html",
    img: "https://www.onlinegames.io/media/posts/519/responsive/Solitaire-Adventure-Tripeaks-xs.jpg" },

  // ---- More sports ----
  { title: "Basketball King", cat: "sports",
    embed: "https://cloud.onlinegames.io/games/2024/construct/316/basketball-king/index-og.html",
    img: "https://www.onlinegames.io/media/posts/907/responsive/basketball-king-xs.jpg" },

  // ---- More clicker ----
  { title: "Evil Santa", cat: "clicker",
    embed: "https://www.onlinegames.io/games/2021/1/evil-santa/index.html",
    img: "https://www.onlinegames.io/media/posts/539/responsive/Evil-Santa-Game-xs.jpg" },

  // ---- More 2 player ----
  { title: "Mini Cars Racing", cat: "2player",
    embed: "https://cloud.onlinegames.io/games/2021/unity/mini-cars-racing/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1010/responsive/Mini-Cars-Racing-xs.jpg" },

  // ---- More simulator / strategy ----
  { title: "Hero Rush Tower Defense", cat: "sim",
    embed: "https://www.onlinegames.io/games/2023/unity/hero-rush-tower-defense/index.html",
    img: "https://www.onlinegames.io/media/posts/491/responsive/Hero-Rush-Tower-Defense-Play-xs.jpg" },
  { title: "Stick Guys Defense", cat: "sim",
    embed: "https://www.onlinegames.io/games/2022/unity3/stick-guys-defense/index.html",
    img: "https://www.onlinegames.io/media/posts/476/responsive/Stick-Guys-Defense-xs.jpg" },
  { title: "Kings io", cat: "sim",
    embed: "https://cloud.onlinegames.io/games/2025/construct/208/kings-io/index-og.html",
    img: "https://www.onlinegames.io/media/posts/952/responsive/Kings-io-xs.jpg" },
  { title: "War of Ships io", cat: "sim",
    embed: "https://www.onlinegames.io/games/2022/unity3/war-of-ships-io/index.html",
    img: "https://www.onlinegames.io/media/posts/509/responsive/War-of-Ships-io-xs.jpg" },
  { title: "Car Wash", cat: "sim",
    embed: "https://www.onlinegames.io/games/2023/unity2/car-wash/index.html",
    img: "https://www.onlinegames.io/media/posts/407/responsive/Car-Wash-Online-Game-xs.jpg" },
  { title: "Rescue Helicopter", cat: "sim",
    embed: "https://www.onlinegames.io/games/2021/2/rescue-helicopter/index.html",
    img: "https://www.onlinegames.io/media/posts/468/responsive/Rescue-Helicopter-xs.jpg" },
  { title: "Tractor Farming Simulator", cat: "sim",
    embed: "https://www.onlinegames.io/games/2022/unity/tractor-farming-simulator/index.html",
    img: "https://www.onlinegames.io/media/posts/552/responsive/Tractor-Farming-Simulator-xs.jpg" },

  // ---- Girls ----
  { title: "Love Tester", cat: "girls",
    embed: "https://www.onlinegames.io/games/2021/3/love-tester/index.html",
    img: "https://www.onlinegames.io/media/posts/152/responsive/love-tester-xs.jpg" },
  { title: "Love Tester Story", cat: "girls",
    embed: "https://cloud.onlinegames.io/games/2024/construct/225/love-tester-story/index-og.html",
    img: "https://www.onlinegames.io/media/posts/816/responsive/Love-Tester-Story-xs.jpg" },
  { title: "Julie Beauty Salon", cat: "girls",
    embed: "https://cloud.onlinegames.io/games/2021/1/julie-beauty-salon/index-og.html",
    img: "https://www.onlinegames.io/media/posts/1011/responsive/Julie-Beauty-Salon-xs.jpg" },
  { title: "Princess Influencer Salon", cat: "girls",
    embed: "https://www.onlinegames.io/games/2021/3/princess-influencer-salon/index.html",
    img: "https://www.onlinegames.io/media/posts/485/responsive/Princess-Influencer-Salon-xs.jpg" },
  { title: "Princesses Prom Night", cat: "girls",
    embed: "https://www.onlinegames.io/games/2021/3/princesses-prom-night/index.html",
    img: "https://www.onlinegames.io/media/posts/498/responsive/Princesses-Prom-Night-xs.jpg" },
  { title: "Princess Beauty Salon", cat: "girls",
    embed: "https://www.onlinegames.io/games/2021/1/princess-beauty-salon/index.html",
    img: "https://www.onlinegames.io/media/posts/525/responsive/Princess-Beauty-Salon-xs.jpg" },
  { title: "Fun Party Makeup", cat: "girls",
    embed: "https://www.onlinegames.io/games/2021/4/fun-party-makeup/index.html",
    img: "https://www.onlinegames.io/media/posts/723/responsive/Fun-Party-Makeup-xs.jpg" },
  { title: "Romantic Secret Kiss", cat: "girls",
    embed: "https://www.onlinegames.io/games/2021/3/romantic-secret-kiss/index.html",
    img: "https://www.onlinegames.io/media/posts/483/responsive/Romantic-Secret-Kiss-xs.jpg" },

  // ============================================================
  // SOURCE 2: GameMonetize (html5.gamemonetize.co — free embeds)
  // Feed: https://rss.gamemonetize.com/rssfeed.php?format=json
  // ============================================================
  { title: "Minecraft Remake", cat: "minecraft",
    embed: "https://html5.gamemonetize.co/cznxajp3hzb8l7gtebaq96s0pbrfa33m/",
    img: "https://img.gamemonetize.com/cznxajp3hzb8l7gtebaq96s0pbrfa33m/512x384.jpg" },
  { title: "Baldi's Basics", cat: "horror", featured: true,
    embed: "https://html5.gamemonetize.co/iiifrxhcnzl5laslqf3eaedtevjzb2bu/",
    img: "https://img.gamemonetize.com/iiifrxhcnzl5laslqf3eaedtevjzb2bu/512x384.jpg" },
  { title: "Among Us Online Edition", cat: "arcade",
    embed: "https://html5.gamemonetize.co/luye5rleios737wp2o9wjq7h577gl937/",
    img: "https://img.gamemonetize.com/luye5rleios737wp2o9wjq7h577gl937/512x384.jpg" },
  { title: "Among Us Space Rush", cat: "arcade",
    embed: "https://html5.gamemonetize.co/3iaqi4b196ujgycgvjnxhegwcj0y4617/",
    img: "https://img.gamemonetize.com/3iaqi4b196ujgycgvjnxhegwcj0y4617/512x384.jpg" },
  { title: "Fall Bros", cat: "arcade",
    embed: "https://html5.gamemonetize.co/vnvpo9h7zc6phugavlw7xni2thz4no4i/",
    img: "https://img.gamemonetize.com/vnvpo9h7zc6phugavlw7xni2thz4no4i/512x384.jpg" },
  { title: "Skate Hooligans", cat: "arcade",
    embed: "https://html5.gamemonetize.co/vy07es6s71vci1su3wzcqrp7e3ym0vtw/",
    img: "https://img.gamemonetize.com/vy07es6s71vci1su3wzcqrp7e3ym0vtw/512x384.jpg" },
  { title: "Tom & Jerry Run", cat: "arcade",
    embed: "https://html5.gamemonetize.co/a6d9kqfsjxbpdktw6p8j11z8bm776t8h/",
    img: "https://img.gamemonetize.com/a6d9kqfsjxbpdktw6p8j11z8bm776t8h/512x384.jpg" },
  { title: "Talking Tom Gold Run", cat: "arcade",
    embed: "https://html5.gamemonetize.co/hn5dh0x6wcnroy3p33ogeyu5z6xsltvw/",
    img: "https://img.gamemonetize.com/hn5dh0x6wcnroy3p33ogeyu5z6xsltvw/512x384.jpg" },
  { title: "Hunter Assassin", cat: "arcade",
    embed: "https://html5.gamemonetize.co/l1c9pkpxysqy1cao2axakpf8mdwkv8qg/",
    img: "https://img.gamemonetize.com/l1c9pkpxysqy1cao2axakpf8mdwkv8qg/512x384.jpg" },
  { title: "Super RunCraft", cat: "minecraft",
    embed: "https://html5.gamemonetize.co/syoymgm7jw290t7mz0hpqjqmc8yqlmrd/",
    img: "https://img.gamemonetize.com/syoymgm7jw290t7mz0hpqjqmc8yqlmrd/512x384.jpg" },
  { title: "MineStrike.fun", cat: "minecraft",
    embed: "https://html5.gamemonetize.co/bgkaq5jchbya9rff5jw6gnkwceukg16s/",
    img: "https://img.gamemonetize.com/bgkaq5jchbya9rff5jw6gnkwceukg16s/512x384.jpg" },
  { title: "12 MiniBattles", cat: "2player",
    embed: "https://html5.gamemonetize.co/nuiyi3o2g6fktyjda55g42v3qe5a3hbq/",
    img: "https://img.gamemonetize.com/nuiyi3o2g6fktyjda55g42v3qe5a3hbq/512x384.jpg" },
  { title: "Drunken Boxing", cat: "2player",
    embed: "https://html5.gamemonetize.co/u7kh677sengcitk8eaib93z7gsiub9f6/",
    img: "https://img.gamemonetize.com/u7kh677sengcitk8eaib93z7gsiub9f6/512x384.jpg" },
  { title: "Squid Game Challenge 3D", cat: "arcade",
    embed: "https://html5.gamemonetize.co/dtemvyguxvsbdnnoilu3s1ygg8umdbvt/",
    img: "https://img.gamemonetize.com/dtemvyguxvsbdnnoilu3s1ygg8umdbvt/512x384.jpg" },
  { title: "Squid Game: Red Light Green Light", cat: "arcade",
    embed: "https://html5.gamemonetize.co/etp56l9axninm4hfoue23ndqkvbpkho2/",
    img: "https://img.gamemonetize.com/etp56l9axninm4hfoue23ndqkvbpkho2/512x384.jpg" },
  { title: "Happy Glass", cat: "puzzle",
    embed: "https://html5.gamemonetize.co/dayksem3hjbea9vsbklh6wqi213w9121/",
    img: "https://img.gamemonetize.com/dayksem3hjbea9vsbklh6wqi213w9121/512x384.jpg" },
  { title: "Love Balls 2D", cat: "puzzle",
    embed: "https://html5.gamemonetize.co/1l6pgl750zi41o2cktmkmr71dntshaej/",
    img: "https://img.gamemonetize.com/1l6pgl750zi41o2cktmkmr71dntshaej/512x384.jpg" },
  { title: "Pull Him Out", cat: "puzzle",
    embed: "https://html5.gamemonetize.co/mhqkw9a80at8pnqcc6jj2uiii5chfai1/",
    img: "https://img.gamemonetize.com/mhqkw9a80at8pnqcc6jj2uiii5chfai1/512x384.jpg" },
  { title: "Hero Rescue Puzzle", cat: "puzzle",
    embed: "https://html5.gamemonetize.co/3596x93682lmj4cn7mrtldmfhviig7jj/",
    img: "https://img.gamemonetize.com/3596x93682lmj4cn7mrtldmfhviig7jj/512x384.jpg" },
  { title: "Homescapes", cat: "puzzle",
    embed: "https://html5.gamemonetize.co/qrhvp96ov1dj1w1u4l2ulb5i4gh9q19g/",
    img: "https://img.gamemonetize.com/qrhvp96ov1dj1w1u4l2ulb5i4gh9q19g/512x384.jpg" },
  { title: "Save The Girl", cat: "girls",
    embed: "https://html5.gamemonetize.co/9ytk0fr25q0r20zbb524x4bxcvpnm5gw/",
    img: "https://img.gamemonetize.com/9ytk0fr25q0r20zbb524x4bxcvpnm5gw/512x384.jpg" },
  { title: "Pou Online", cat: "sim",
    embed: "https://html5.gamemonetize.co/jyeazqa0x7ym5xcq22g9mgv74s5tift1/",
    img: "https://img.gamemonetize.com/jyeazqa0x7ym5xcq22g9mgv74s5tift1/512x384.jpg" },
  { title: "Bike Race Rush", cat: "driving",
    embed: "https://html5.gamemonetize.co/4bb52narsr9s57z5y7qlch5zhupiucld/",
    img: "https://img.gamemonetize.com/4bb52narsr9s57z5y7qlch5zhupiucld/512x384.jpg" },
  { title: "Roof Rails", cat: "arcade",
    embed: "https://html5.gamemonetize.co/3zsuu4fl12ujvfaa5yett2t1rclzg9jj/",
    img: "https://img.gamemonetize.com/3zsuu4fl12ujvfaa5yett2t1rclzg9jj/512x384.jpg" },
  { title: "Jumper Jam", cat: "arcade",
    embed: "https://html5.gamemonetize.co/vz014sa1b6hbw3jquxwgn98xhzux2uhz/",
    img: "https://img.gamemonetize.com/vz014sa1b6hbw3jquxwgn98xhzux2uhz/512x384.jpg" },
  { title: "Push the Crazy Crowd", cat: "arcade",
    embed: "https://html5.gamemonetize.co/91juk8nwy961yt1uu7jloxvwoe3awabu/",
    img: "https://img.gamemonetize.com/91juk8nwy961yt1uu7jloxvwoe3awabu/512x384.jpg" },
  { title: "Zombie Bears Night Shooting", cat: "shooting",
    embed: "https://html5.gamemonetize.co/a8i3hhixhynwz435k72ub0ichgummyfw/",
    img: "https://img.gamemonetize.com/a8i3hhixhynwz435k72ub0ichgummyfw/512x384.jpg" },

  // ============================================================
  // SOURCE 3: TurboWarp (Scratch project embeds — CC BY-SA)
  // Embed pattern: https://turbowarp.org/{projectId}/embed
  // IDs verified via api.scratch.mit.edu
  // ============================================================
  { title: "Paper Minecraft", cat: "minecraft", featured: true,
    embed: "https://turbowarp.org/10128407/embed",
    img: "https://cdn2.scratch.mit.edu/get_image/project/10128407_480x360.png" },
  { title: "Appel", cat: "arcade",
    embed: "https://turbowarp.org/60917032/embed",
    img: "https://cdn2.scratch.mit.edu/get_image/project/60917032_480x360.png" },
  { title: "Getting Over It", cat: "arcade",
    embed: "https://turbowarp.org/389464290/embed",
    img: "https://cdn2.scratch.mit.edu/get_image/project/389464290_480x360.png" },
];

// slug used for URL hash (#play=highway-traffic)
GAMES.forEach(g => {
  g.slug = g.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
});
